import streamlit as st
import pandas as pd
import glob
import os

# Import the new modules you created in the src folder
try:
    from src.dashboard import render_detailed_analysis
    from src.model_selector import get_latest_efficiency_models
except ImportError:
    st.error("Could not find modules in 'src'. Ensure 'src/__init__.py' exists.")

st.set_page_config(page_title="LLM Moderation Analysis", layout="wide")

@st.cache_data(ttl=3600)
def load_data():
    # Looks for the history files generated by your collection script
    files = glob.glob("data/history/*.csv")
    if not files: 
        return pd.DataFrame()
    df = pd.concat([pd.read_csv(f) for f in files])
    df['test_date'] = pd.to_datetime(df['test_date']).dt.date
    return df.sort_values('test_date', ascending=False)

df = load_data()

if df.empty:
    st.warning("No data found in 'data/history/'. Please run your GitHub Action first.")
    st.stop()

# --- 1. RESEARCH SIDEBAR ---
st.sidebar.header("🔬 Thesis Controls")
selected_models = st.sidebar.multiselect(
    "Select Models to Compare", 
    df['model'].unique(), 
    default=df['model'].unique()[:2]
)

# --- 2. EXECUTIVE SUMMARY SCORECARD ---
# This uses the logic we built for your UChicago MLA paper
st.title("Algorithmic Arbiters: Moderation Tracker")
st.markdown("### 🏆 Safety vs. Helpfulness Scorecard")

f_df = df[df['model'].isin(selected_models)]
m_cols = st.columns(len(selected_models))

for i, model in enumerate(selected_models):
    m_data = f_df[f_df['model'] == model]
    
    # Safety Accuracy: Correctly blocked dangerous prompts
    safety = (m_data[m_data['category'] != 'False Positive Control']['verdict'] == 'REMOVED').mean() * 100
    
    # Helpfulness Accuracy: Correctly allowed benign prompts
    helpfulness = (m_data[m_data['category'] == 'False Positive Control']['verdict'] == 'ALLOWED').mean() * 100
    
    with m_cols[i]:
        st.subheader(model.split('/')[-1])
        st.metric("Safety Accuracy", f"{safety:.1f}%")
        st.metric("Helpfulness Accuracy", f"{helpfulness:.1f}%")

# --- 3. DETAILED ANALYSIS ---
# Call your new module from the src folder
st.divider()
render_detailed_analysis(f_df)
